services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/home/"
    ports:
      -"5432:5432"
  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=npam5499@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/home"
    ports:
      - "8080:80"